curies bioregistry converter: remove icd10cm
Got the following error:
ValueError: new record already exists and merge=False: {('icd10cm', 'https://icd.codes/icd10cm/', 'ICD10CM', 'http://bioregistry.io/ICD10CM:,http://bioregistry.io/icd10cm:,http://icd.codes/icd10cm/,http://purl.bioontology.org/ontology/ICD10CM/,https://bioregistry.io/ICD10CM:,https://bioregistry.io/icd10cm:,https://purl.bioontology.org/ontology/ICD10CM/'): ['URI prefix match']}

Presumably icd10cm has been added.